set_property SRC_FILE_INFO {cfile:/home/furiosa/Projects/shitatechnology/work/ctrl/board/XDC/pin.xdc rfile:../../../../XDC/pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R4 [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports key]
